### PR TITLE
Make rpmalloc C90 compliant, use pragma once, proper C++ checking.

### PR DESCRIPTION
**Pull request by czipperz**
My project uses C90 and as such cannot use a C11 project.  I went through the entire source and converted it into C90.

The second commit adds at the beginning

    #pragma once
    
    #ifdef __cplusplus
    extern "C" {
    #endif

and at the end

    #ifdef __cplusplus
    }
    #endif

See issue #22

### CODE REVIEW

**Comment by MJansson** [comment]
What are you compiling for that needs a high-performance malloc but doesn't gave c99 or c11 support? I'm more inclined to go the other way and use c11 more to remove the platform specific atomics.

**Comment by czipperz** [comment]
I don't need a high performance malloc, but it's always nice to have.  It's fine if you don't accept this pull.  I do suggest that you cherry-pick the second commit.

AFAIK Windows still only supports C90 (with very few C99 features) and I wish to make my little libraries cross platform.

If you want platform independent atomics, maybe you should use glib: https://developer.gnome.org/glib/stable/glib-Atomic-Operations.html.

**Comment by MJansson** [comment]
Yes, for Microsoft compiler some wrappers would be needed.

Regarding the c++ wrapper in the header, wouldn't it be preferable to have the wrap after the #include <stddef.h> to avoid any issues wrapping a system header in the extern block?

**Comment by czipperz** [comment]
Isocpp says to not wrap it for stylistic purposes. So you are right.

**Comment by MJansson** [comment]
Made a change with the extern wrap after the include in master branch. C90 is not a goal of mine so will not apply the other changes (rather, as I mentioned, will move towards C11).

**Pull request closed without merging**
